### ISSUE TITLE
Can't find your repo in cocoapods.

### ISSUE THREAD

**Issue by dukewan** [cjcoax/Autocomplete#1]
Hi, it seems to be a wonderful library. But I can't install it using cocoapods. Why?

**Comment by cjcoax** [comment]
It should be good now! Happy you liked it!

**Comment by dukewan** [comment]
I updated the pod file and it was successfully installed using `pod install` just now. I tried to search your pod in the cocoaspod website before, but I can't find it so I thought I can't install it. :D
