### ISSUE TITLE
Trouble building project after clean pod install

### ISSUE THREAD

**Issue by Thisura98** [cjcoax/Autocomplete#12]
I am having trouble using this pod in my project, with compiling it under Swift 4. The following are the errors I keep getting:

![Screen Shot 2019-04-29 at 7 17 24 PM](https://user-images.githubusercontent.com/16175314/56900501-9f8cb600-6ab3-11e9-8edb-d1ed274743a2.png)

Please let me know if I am doing something wrong. I am using version 0.0.4 of this pod.

**Comment by Thisura98** [comment]
I think I found the issue. It seems you have fixed these issues in the latest commit but running `pod install` still refers to commit e2b2c4d.

Would it be possible to release a new version with the latest changes?

**Comment by cjcoax** [comment]
Thanks for reporting, it should be fixed.
